config/routes.rb
StudentforumWeb::Application.routes.draw do
   root :to => "pages#index"

  match "/services"=>"Pages#services" ,:via=>:get
  match "/about_us"=>"Pages#about_us" ,:via=>:get
  match "/contact_us"=>"Pages#contact_us" ,:via=>:get
  match "/team"=>"Pages#team" ,:via=>:get
  match "/testimonials"=>"Pages#testimonials" ,:via=>:get
  match "/thank_you"=>"Pages#thank_you" ,:via=>:post

   match ':controller(/:action(/:id(.:format)))'
end

app/models/visitor.rb
# To change this template, choose Tools | Templates
# and open the template in the editor.

class Visitor < ActiveRecord::Base
  attr_accessible :name,:phone,:email,:comment,:college
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  layout "page" 
  def index
    render :layout=>"application"
  end

  def services
    @title="Services"
  end

  def about_us
    @title="About Us"
  end

  def contact_us
    @title="Contact Us"
  end

  def blog

  end

  def team
    @title="Team"
  end

  def testimonials
    @title="Testimonials"
  end

  def thank_you
    @title="Thank You"
    Visitor.create(params[:visitor])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" dir="ltr">
  <head>
    <title>Students'Forum</title>
    <meta name="google-site-verification" content="VDqho9glCafpab-MweASxWTEfo_L8RRmjSWao6wV5jk" />
<%# stylesheet_link_tag :all %>
<%# csrf_meta_tag %>
    <link href="stylesheets/style.css" rel="stylesheet" type="text/css"/>
    <link href="stylesheets/slider.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29244214-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  </head>
    <body id="home" class="b">
    <%=render(:partial=>'header')%>
    <%= yield %>
    <%=render(:partial=>'footer')%>
  </body>
    <script type="text/javascript" src="javascripts/jquery.js"></script>
    <script type="text/javascript" src="javascripts/magik.js"></script>
    <script type="text/javascript" src="javascripts/custom.js"></script>
</html>

app/views/layouts/page.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" dir="ltr">
  <head>
    <title>Students'Forum</title>
<%# stylesheet_link_tag :all %>
<%# csrf_meta_tag %>
    <link href="stylesheets/style.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript" src="javascripts/jquery.js"></script>
    <script type="text/javascript" src="javascripts/magik.js"></script>
    <script type="text/javascript" src="javascripts/custom.js"></script>

    <link href="stylesheets/slider.css" rel="stylesheet" type="text/css"/>
    <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29244214-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
  </head>
  <body>
    <%=render(:partial=>'header')%>
    <%=render(:partial=>'title',:locals => {:title => @title})%>
    <div id="container">
      <div id="mainContent" class="clearfix">
        <%=render(:partial=>'lhs_col',:locals => {:title => @title} )%>
        <div class="RHS_box">
        <%= yield %>
        </div>
      </div>
      </br>
    </div>
    <%=render(:partial=>'footer')%>
  </body>
</html>

app/views/pages/_footer.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<div id="footer">
  <div class="section">
    <div class="col" style="width:320px">
      <h5><img src="images/footer_logo123.png" width="200px" /></h5>
      <div class="top_space">

      </div>
      <div>
        <h6>Contact</h6>
        <div class="top_space1">
          <span style="color:#f9e826">+91 758-808-4080</span>
          <br />
          <a href="mailto:info@studentsforumonline.com" style="font-size:14px">info@studentsforumonline.com</a>
        </div>
      </div>
    </div>
    <div style="float:left; overflow:hidden; width:300px; margin-right:40px">
      <div class="col" style="width:130px">
        <h5>Learn More</h5>
        <div class="top_space">
          <%= link_to  "Home" ,root_url ,:title=>"Home"%>
          <br />
          <%= link_to "About us",about_us_url%>
          <br />
          <%= link_to "Services",services_url%>
          <br />
          <%= link_to "Testimonials",testimonials_url%>
          <br />

        </div>
      </div>
      <div class="col" style="width:140px; margin-right:0px">
        <h5>&nbsp;</h5>
        <div class="top_space">
          <%= link_to "Team",team_url%>
          <br />
          <%= link_to "Contact us",contact_us_url%>
          <br />
          <a target="_blank" href="http://twitter.com/studentsforumSF" title="Students Forum twitter">Follow us on twitter</a>
          <br />
          <a target="_blank" href="http://www.facebook.com/studentsforum" title="facebook">Fan us on Facebook</a>
        </div>
      </div>

      <div style="clear:both">
        &nbsp;
      </div>
      <div class="social_icon">
        <a target="_blank" href="http://twitter.com/studentsforumSF" title="twitter"><img src="images/twitter_32.png" /></a> &nbsp;&nbsp; <a target="_blank" href="https://www.facebook.com/studentsforum" title="facebook"><img src="images/facebook_32.png" /></a> &nbsp;&nbsp; <!--img src="images/linkedin_32.png" / -->
      </div>
    </div>
    <div class="col" style="margin-right:0px; width:250px">
      <h5>Testimonials</h5>
      <div class="footer_testimonials">
							"SF has done a incredible job of providing pre placement training to my students.They provide precise resources and company specific training which prepares the students well before hand. I can't recommend it enough."
      </div>
    </div>
  </div>
</div>

app/views/pages/_header.html.erb
<div id="header">
			<div id="header_inner">
				<h3 style="margin-top:3px">
					<%=link_to image_tag("logo123.png", :border => 0,:height=>55), root_url%>
					</h3>
				<ul id="mainNav" class="tabs">
					<li class="<%= controller.class == PagesController and controller.action_name == 'index' ? 'current_home' : '' %>">
						<%= link_to root_url,:class=>"home" ,:title=>"Home" do %>
						<span>Home</span>
						<%end%>                       
					</li>

                                        <li class="<%= controller.class == PagesController and controller.action_name == 'about_us' ? 'current_home' : '' %>">
						<%= link_to about_us_url,:title=>"Services" do %>
						<span>About Us</span>
						<%end%>
					</li>

					<li class="<%= controller.class == PagesController and controller.action_name == 'services' ? 'current_home' : '' %>">
						<%= link_to services_url,:title=>"Services" do %>
						<span>Services</span>
						<%end%>
					</li>

					<li class="<%= controller.class == PagesController and controller.action_name == 'blog' ? 'current_home' : '' %>">
						<%= link_to "",:title=>"Blog" do %>
						<span>Blog</span>
						<%end%>
					</li>

					<li class="<%= controller.class == PagesController and controller.action_name == 'contact_us' ? 'current_home' : '' %>">
						<%= link_to contact_us_url,:title=>"Contact" do %>
						<span>Contact Us</span>
						<%end%>
					</li>

					<li class="top_space2">
						&nbsp; <img src="images/phone.png" />
					</li>
				</ul>
			</div>
		</div>

app/views/pages/_lhs_col.html.erb
<div id="LHS_col">
  <ul class="sub-nav">
    <li class="<%= controller.class == PagesController and controller.action_name == 'index' ? 'active' : '' %>">
      <%= link_to "Home",root_url,:title=>"Home"%>
    </li>
    <li class="<%= controller.class == PagesController and controller.action_name == 'about_us' ? 'active' : '' %>">
      <%= link_to "About Us",about_us_url,:title=>"About Us"%>
    </li>
    <li class="<%= controller.class == PagesController and controller.action_name == 'services' ? 'active' : '' %>">
      <%= link_to "Services",services_url,:title=>"Services"%>
    </li>
    <li >
      <%= link_to "Blog","",:title=>"Blog"%>
    </li>
    <li class="<%= controller.class == PagesController and controller.action_name == 'testimonials' ? 'active' : '' %>">
      <%= link_to "Testimonials",testimonials_url,:title=>"Testimonials"%>
    </li>
    <li class="<%= controller.class == PagesController and controller.action_name == 'team' ? 'active' : '' %>">
      <%= link_to "Team",team_url,:title=>"Core Team"%>
    </li>
    <li class="<%= controller.class == PagesController and controller.action_name == 'contact_us' ? 'active' : '' %>">
      <%= link_to "Contact Us",contact_us_url,:title=>"Contact Us"%>
    </li>
  </ul>
</div>

app/views/pages/_title.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<div id="content" class="clearfix">
  <div class="relative_inner">
    <div id="inner_content">
      <h1><%=@title%></h1>
      <div id="twitter-blog" style="width: 168px; padding-right: 10px; padding-left: 25px; padding-top: 100px;">
						Follow us
        <br>
        <a target="_blank" href="http://twitter.com/StudentsforumSF" title="twitter">@StudentsforumSF</a>

      </div>
    </div>
  </div>
</div>

app/views/pages/about_us.html.erb
<h2>Students' Forum</h2>
<div>
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  As engineers we know how hard it is to get placed in your dream company. We understand that where you start-out will more often than not decide how your career will take shape. But where there are problems we find solutions,after-all that is what engineers do.We understand your problems because we have faced them.
  <br />
  <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  Student’s Forum (SF) has helped nearly 5000 students from premier institutes in Pune like VIT,VIIT and SIT. 
  We provide several services to help students focus such as resume streamlining, in-depth and company specific aptitude
  preparation, connecting students with others who have been through the process and are currently working in the
  company of choice, we teach various self-development techniques that help students to identify and improve on
  their shortcomings through personal interaction.SF also helps to polish soft skills of those candidates
  that are “rough-around-the edges “ to help you achieve your true potential.
  <br /><br />
  <h5>What SF does?</h5>
  <br />
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  We at SF help candidates to prepare for the entire placement process by holding mock interviews, group discussions and
  personal interviews so that when you face that all important job interview you are truly and completely ready.
  We instruct you giving you several rules of thumb on the “do’s and don’ts” of any interview.
  We give handy tips on all the minute details regarding the candidate’s appearance and grooming thereby
  ensuring that he or she makes a lasting impression on the employer.
  <br />

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        SF prepares candidates for  group discussions as well by teaching them several techniques to help them
      put across their point of view in a manner that is concise, correct and refined .
    Connecting with alumni of an organization is one of the unique features of SF.
    SF is different from others in that it provides a tailor made solution to your problems through personal interaction it ensures that the individual’s needs are catered to.
     SF also provides you answers to any queries that you may have via its open forum. We are your 24*7 online placement helpline.
  
<br />
  <br />

</div>

app/views/pages/contact_us.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<div id="contact_us">

  <h2>Contact US</h2>
  <div>
			To get a demo of the sessions and events in your college ,simply fill out the following form.We will contact you within 24 hrs.For any questions call +91 758-808-4080
  </div>
  
  <div class="big_font"><img src="images/phone_icon1.png"  align="absmiddle"/>+91 758-808-4080  &nbsp;&nbsp;
   <img src="images/email_icon1.png"  align="absmiddle"/><a href="mailto:info@studentsforumonline.com">info@studentsforumonline.com</a>
  </div>
  

  <%= form_tag(thank_you_url,:method=>"post") do %>
    <ul style="padding-top:5px">
      <li class="label">
        Name:
      </li>

      <li>
        <span class="wrap1"> <input align="absbottom"  required="true" class="inputbox" id="email_name" name="visitor[name]" size="30" style="width:270px" title="Enter name" type="text" /> </span>
      </li>
    </ul>
    <ul>
      <li class="label">
        College:
      </li>

      <li>
        <span class="wrap1"> <input align="absbottom" class="inputbox" id="visitor_company" name="visitor[college]" size="30" style="width:270px" title="Enter company name" type="text" /> </span>
      </li>
    </ul>
    <ul>
      <li class="label">
        Email address:
      </li>

      <li>
        <span class="wrap1"> <input align="absbottom" required="true" class="inputbox" id="email_email" name="visitor[email]" size="30" style="width:270px" title="Enter email address" type="email" /> </span>
      </li>
    </ul>
    <ul>
      <li class="label">
        Phone number:
      </li>

      <li>
        <span class="wrap1"> <input align="absbottom" class="inputbox" id="email_phone" name="visitor[phone]" size="30" style="width:270px" title="Enter Phone Number" type="text" /> </span>
      </li>
    </ul>


    <ul>
      <li class="label">
        Comment:
      </li>

      <li>
        <span class="wrap2" style="width:450px;"> 					<textarea name="visitor[comment]"  id="email_question" class="txt_area" title="Write us a note about your requirement" style = "width:440px"></textarea> </span>
      </li>
    </ul>

    <ul style="padding-top:5px;">
      <li class="label">
        &nbsp;
      </li>
      <li style="">
        <input align="absmiddle" border="0"  type="image" src="images/submit_button.png" />
      </li>
    </ul>

  <%end%>
</div>

app/views/pages/index.html.erb
<div id="content" class="clearfix">
  <div class="relative">
    <div style="width:940px; margin:auto; overflow:hidden; padding-bottom:70px">
      <div style="position: relative;" id="slider-wrapper">
        <div style="width:940px; height:auto !important" id="slider">
          <ul style="width: 2880px; margin-left: 0px;">
            <li style="margin-left: -0px; float: left;">
              <div id="landingContent">
                <div style="float:left; padding-top:10px; width:410px;">
                  <img src="images/slide1.png" width="410" />
                </div>
                <div id="sideCopy">
                  <div style="padding-top:10px">
                    <h1>Pre Placement Training That Gives You The Edge </h1>
                    <div  style="padding-top:10px">
			Provides the Pre-Placement Training in all  the required skill sets,so that you land that perfect first job
                    </div>
                  </div>
                  <br />
                </div>
              </div>
            </li>
            <li style="float: left;">
              <div id="landingContent1">
                <div style="float:left; padding-top:10px; width:410px;">
                  <img src="images/slide2.png" height="230" />
                </div>
                <div id="sideCopy">
                  <div style="padding-top:10px">
                    <h1>Loads Of Relevant Resources</h1>
                    <div  style="padding-top:10px">
			We provide you with tons of resources for learning and connect every candidate to their institute’s alumni and previously selected candidates thereby helping them improve their professional network.
                    </div>
                  </div>
                  <br />
                </div>
              </div>
            </li>
            <li style="float: left;">
              <div id="landingContent">
                <div style="float:left; padding-top:10px; width:410px;">
                  <img src="images/slide3.jpg" width="300" />
                </div>
                <div id="sideCopy">
                  <div style="padding-top:10px">
                    <h1>Analysis That Help You Grow </h1>
                    <div  style="padding-top:10px">

                      SF provides one-to-one analysis for each candidate to help them identify their weaknesses and strengths thereby helping them develop in a holistic manner

                    </div>
                  </div>
                  <br />
                </div>
              </div>
            </li>
            <li style="float: left;">
              <div id="landingContent">
                <div style="float:left; padding-top:20px; width:410px;">
                  <img src="images/slide4.png" height="230" />
                </div>
                <div id="sideCopy">
                  <div style="padding-top:10px">
                    <h1>Transforming You For The Professional World </h1>
                    <div  style="padding-top:10px">
			 SF also helps to polish soft skills of those candidates that are "rough-around-the edges" to help you achieve your true potential.
                    </div>
                  </div>
                  <br />
                </div>
              </div>
            </li>
          </ul>
        </div>
      </div>

      <div id="twitter-blog" style="width: 168px; padding-right: 10px; padding-left: 25px; padding-top: 100px;">
						Follow us
        <br>
        <a target="_blank" href="http://twitter.com/StudentsforumSF" title="twitter">@StudentsforumSF</a>

      </div>
    </div>
  </div>
</div>
<div id="container">
  <div id="mainContent" class="clearfix top_space2">
    <h2><img src="images/SF.png" /></h2>
    <div class="whiteBox">
      <div style="width:940px">

        Students' Forum(SF) is a unique platform for students to discuss industry placements in terms that students understand. “Made  by engineers for engineers is what makes us different”.Our experience in various placement related areas will help you land that all important first job. Our training sessions and events help students to get polished and channelled in the right direction so that ,they can face anything that the competitive job market of today throws at them.


      </div>
      <ul id="key_benefits_list">
        <li>
          <h6 class="build">What we do?</h6> 
          Conduct Pre-Placement Session similar to campus placement session.
          Session includes Aptitude Test, Discussion of Aptitude Test, GD, PI.
          We will provide analysis at individual and institute level.
          Interaction between alumni and the final year students through online
          and offline activities.

        </li>
        <li style="padding-right:20px">
          <h6 class="maximize">What we want to achieve?</h6>
          <ul>
            We provide students with first hand experience of the placement
            process providing exposure to what they may face during campus
            placements.
            Making students aware about their preparations and allowing them to
            improve on the areas required.
            It will add value to the preparation level of students and indirectly to the
            institution.
          </ul>
        </li>
        <li>
          <h6 class="sales"> How we plan to do?</h6>
          An eight-hour session on a single day comprising of an entire placement procedure.
          Providing analysis to an individual and institute.
          Allowing students to interact with seniors and share information via
          forum specific to their college.
          May provide documents on Resume-writing and GD preparation.

        </li>
      </ul>

    </div>

  </div>
  <br />
  <div>
    <h3><img src="images/testimonials.png"></h3>
  </div>
  <div style="overflow:hidden; width:940px; margin:auto">
    <div id="testimonial_list" style="width:480px">
      <div>
        <h3><img class="quote_img" src="images/quote_icon_left.png"> I think SF is a brilliant and unique platform for students to exchange information regarding the placement process. This process isn't  as simple as it looks, but in reality it requires a lot of preparation on the part of the student.As a placement officer we would like that our students are not merely placed but placed according to their skill where they can utilize their knowledge, grow within the organization and contribute to society.
          <img align="middle" src="images/quote_icon_right.png"></h3>
      </div>
      <div style="overflow: hidden; margin-top:5px">
        <p style="float: right; padding-top:5px; width:230px;margin-top:15px;border-left:1px #eaeaea solid; padding-left:15px; padding-bottom:5px">
          <strong><em> Prof. Pawar Virendra D,</em></strong>
          <br>
							Training & Placement Officer,
          <br>
							Vishwakarma Institute of Technology.
        </p>
        <div style="float: left; padding-top:0px; width:220px"><img align="right" src="images/vit.png">
        </div>
      </div>
    </div>
    <div style="float:right" id="testimonial_list">
      <div>
        <h3><img class="quote_img" src="images/quote_icon_left.png"> I am thoroughly impressed with the features that this group offers and would definitely recommend it very highly to all my students. Experience is a vital resource in today’s world and a group like SF helps students make that all important transition from being a student to being a professional that is industry-ready. <img align="middle" src="images/quote_icon_right.png"></h3>
      </div>
      <div style="overflow: hidden; margin-top:15px;">
        <p style="float: right; padding-top:5px; width:210px; border-left:1px #eaeaea solid; padding-left:15px; padding-bottom:5px">
          <strong><em>Prof. Brijesh M. Deore,</em></strong>
          <br>
							Training & Placement Officer,
          <br>
							S.K.N College of Engineering .
          <br>
                                                        (Sinhgad Technical Education Society)
        </p>
        <div style="float: left; padding-left:10px; width:160px"><img align="right" src="images/sit.png">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/services.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<h1 style="font-size: 20px">Discovering the procedure</h1>
<br />
&nbsp;&nbsp; SF  provides candidates with detailed and specific information regarding each company’s placement procedure.We take a mock
placement procedure including Aptitude test HR interviews ,Technical interviews,Group discussions.
This gives candidates the placement experience before the real game begins.

<br /><br />
<h1 style="font-size: 20px"> Beat the Test!!</h1>
<br />
&nbsp;&nbsp;We help candidates focus on the test-areas that matter helping students to score higher thereby improving their chances.
<br /><br />
<h1 style="font-size: 20px">In-depth Personal Analysis </h1>
<br />
&nbsp;&nbsp;SF provides one-to-one analysis for each candidate to help them identify their weaknesses and strengths. A detail report is generated for every student as well as on the institute level. We analyze each candidate's resume and help them highlight themselves separating them from the rest.
<br /><br />
<h1 style="font-size: 20px">Helping you grow</h1>
<br />
&nbsp;&nbsp;We advise students on how to improve on their resumes by providing them with industry relevant information to help candidates sharpen their skills.We also provide rigorous training to help you reach your true potential.
<br /><br />
<h1 style="font-size: 20px">Offline - Online connection.</h1>
<br />
After an event in your campus we connect every candidate to their institute’s alumni thereby helping them improve their professional network.Alumni are encouraged to share valuable information that can be learned only through experience.We at SF stress on the importance of sharing information and believe that knowledge truly empowers.
Queries can be asked on our online platform related to any placement specific area ,we make sure that they are answered by our experts.

app/views/pages/team.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<h1>Team</h1>
</br>
</br>
<ul>
  <li>Ankush Zanwar</li></br>
  <li>Rohit Nayak</li></br>
  <li>Deepak Shinde</li></br>
  <li>Satprakash Arora</li></br>
  <li>Sudhir Deshpande</li></br>
  <li>Jaai Phatak</li></br>
  <li>Pritam Baddewar</li></br>
  <li>Yatish Mehta</li></br>
</ul>

app/views/pages/testimonials.html.erb
<h1>Testimonials</h1>
</br>
</br>
<div class="testimonialsListTestimonial" style="font-style: italic ">
  <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Students' Forum is the helping hand I got and I am grateful to the group.
    The best place where I could get help,clear my doubts about any small thing
    starting from current events to doubts in any domain.
    It helped me to avoid mistakes because they were there to guide us.
    This is the best platform I ever had to communicate with the right person related to placements
    and acquire the needed help – I really felt taken care because of SF"
  </p>
  <strong>
    <span class="client" style="font-family: Gill,Helvitica ;font-style: normal;font-size: 15px">
      Athashri Halale,</br>
      VIT,Pune</br>
      Cognizant.
    </span>
  </strong>
</br>
</br>
  <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Student Forum is a great place for students as we not 
    only get information about tests but we also get information about interview procedure.
    They provide company specific informations and thats very unique according to me.
    Students' Forum helped me and all students from 2012 batch in our placements. Thanks SF"
  </p>
  <strong>
    <span class="client" style="font-family: Gill,Helvitica ;font-style: normal;font-size: 15px">
      Prathamesh Sonpatki,</br>
      VIT,Pune</br>
      S1 Services.
    </span>
  </strong>

</div> 

app/views/pages/thank_you.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<h2>Thank you</h2>
</br>
Thank you for your interest in StudentsForum.We will surely get in contact with you as soon as possible.